import type { Metadata } from "next";
import "./globals.css";
import { getSession } from "@/lib/getSession";
import NavBar from "@/components/navbar/NavBar";
import { Poppins } from "next/font/google";

const poppins = Poppins({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-poppins",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getSession();
  if (session?.user) {
    return (
      <html lang="en">
        <body className={poppins.variable}>
          <div
            className="h-screen bg-cover bg-center"
            style={{ backgroundImage: `url(/images/background2.jpg)` }}
          >
            <div className="h-[9vh]">
              <NavBar />
            </div>
            <div className="h-[91vh]">{children}</div>
          </div>
        </body>
      </html>
    );
  } else {
    return (
      <html lang="en">
        <body className={poppins.variable}>
          <div
            style={{ backgroundImage: `url(/images/background1.png)` }}
            className="h-screen bg-cover bg-center"
          >
            {children}
          </div>
        </body>
      </html>
    );
  }
}
